FROM alpine:3.8
MAINTAINER "Peter Schiffer" <peter@rfv.sk>

RUN apk add --no-cache \
    pdns-recursor \
    python3

RUN pip3 install --no-cache-dir envtpl

RUN mkdir -p /etc/pdns/api.d \
  && chown -R recursor: /etc/pdns/api.d

ENV VERSION=4.1 \
  PDNS_setuid=recursor \
  PDNS_setgid=recursor \
  PDNS_daemon=no

EXPOSE 53 53/udp

COPY recursor.conf.tpl /
COPY docker-cmd.sh /

CMD [ "/docker-cmd.sh" ]
