name: Docker Image CI for PRs

on:
  pull_request:
    branches: [ master ]

jobs:

  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - recursor-fedora
          - recursor-alpine
          - mysql-fedora
          - mysql-alpine
          - pgsql-fedora
          - pgsql-alpine
          - admin
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6
      - name: Run image end-to-end test
        run: tests/e2e.sh ${{ matrix.target }}
